### ISSUE TITLE
[BUG] Scope unusability

### ISSUE THREAD

**Issue by TomekHar** [Paneedah/paneedah-modern-warfare#18]
**Version:** [mw3.0-0.5.0.0]

**Describe the bug**
Optics are unusable on certain guns.

**To Reproduce**
1. Get an affected gun
2. Put any optic on it
3. Aim down sights.

**Expected behavior**
I expected a clear view trough the optic.

**Screenshots / Videos**
![Zrzut ekranu (4)](https://user-images.githubusercontent.com/77067512/220757292-5e0be84d-257c-43da-b74b-4647995ab4b2.png)
![Zrzut ekranu (80)](https://user-images.githubusercontent.com/77067512/220757499-62be3abf-ef79-44a1-837d-3a0181f93c6f.png)

**Additional context**
-

**Comment by Paneedah** [comment]
This is not a bug.
