### ISSUE TITLE
[BUG] Magazines (mainly drums) clip into arms

### ISSUE THREAD

**Issue by TomekHar** [Paneedah/paneedah-modern-warfare#23]
**Version:** [mw3.0-0.5.0.0]

**Describe the bug**
Drum magazines clip into arms of the shooter.

**To Reproduce**
1. Get an affected gun
2. Load a drum magazine

**Expected behavior**
The magazines are not supposed to clip into the shooter's arms.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/77067512/220761421-5e5375ed-5f9a-4727-aa5e-fa1322d32c39.png)

**Additional context**
-

**Comment by Paneedah** [comment]
Not worth the time to fix for such a minor visual glitch.
