### ISSUE TITLE
[FEATURE] Add Chinese language file for mod

### ISSUE THREAD

**Issue by Koud-Wind** [Paneedah/paneedah-modern-warfare#46]
**Is your feature request related to a problem? Please describe.**
More language support

**Describe the solution you'd like**
Add Chinese language file for mod

**Describe alternatives you've considered**
N/A

**Additional context**
[TW&CN.zip](https://github.com/Paneedah/paneedah-modern-warfare/files/10813409/TW.CN.zip)

**Comment by ChromaPIE** [comment]
It's just not it. I'm overhauling the whole locale soon.
