### ISSUE TITLE
[BUG] Incompatibility with Nuclear Tech Mod (And how to fix)

### ISSUE THREAD

**Issue by PineappleCat22** [Paneedah/paneedah-modern-warfare#79]
**Version:** 0.1-Dev 5

**Describe the bug**
The MW rain effects clash with NTM Reloaded when a nuclear bomb is detonated that would otherwise cause rain.

**To Reproduce**
1. Create a world with NTM Reloaded and Paneedah Modern Warfare
2. Detonate a bomb
3. See crash

**Expected behavior**
Game does not crash.

**Temporary Solution**
Bug can be fixed by editing the config and setting enableFancyRainAndSnow and onScreenRainAndSnow to false.

**Log file**
[latest.log](https://github.com/Paneedah/paneedah-modern-warfare/files/11470599/latest.log)

**Comment by Desoroxxx** [comment]
@Paneedah please archive this repo so no one can post issues here
As for @PineappleCat22 head to the new repo with the newer version Dev-11
https://github.com/Cubed-Development/Modern-Warfare-Cubed/releases/tag/0.1-Dev-11
